<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('axy_mi_mis', function (Blueprint $table) {
            $table->id();
            $table->string('axy_mi_mi_a')->nullable();
            $table->string('axy_mi_mi_b')->nullable();
            $table->string('axy_mi_mi_c')->nullable();
            $table->string('axy_mi_mi_d')->nullable();
            $table->string('axy_mi_mi_e')->nullable();
            $table->string('axy_mi_mi_f')->nullable();
            $table->double('axy_mi_mi_g')->nullable();
            $table->double('axy_mi_mi_h')->nullable();
            $table->double('axy_mi_mi_i')->nullable();
            $table->double('axy_mi_mi_j')->nullable();
            $table->double('axy_mi_mi_k')->nullable();
            $table->double('axy_mi_mi_l')->nullable();
            $table->double('axy_mi_mi_m')->nullable();
            $table->double('axy_mi_mi_n')->nullable();
            $table->double('axy_mi_mi_o')->nullable();
            $table->double('axy_mi_mi_p')->nullable();
            $table->double('axy_mi_mi_q')->nullable();
            $table->string('axy_mi_mi_r')->nullable();
            $table->string('axy_mi_mi_s')->nullable();
            $table->string('axy_mi_mi_t')->nullable();
            $table->string('axy_mi_mi_u')->nullable();
            $table->string('axy_mi_mi_v')->nullable();
            $table->float('axy_mi_mi_w')->nullable();
            $table->float('axy_mi_mi_x')->nullable();
            $table->float('axy_mi_mi_y')->nullable();
            $table->float('axy_mi_mi_z')->nullable();
            $table->float('axy_mi_mi_aa')->nullable();
            $table->float('axy_mi_mi_ab')->nullable();
            $table->float('axy_mi_mi_ac')->nullable();
            $table->float('axy_mi_mi_ad')->nullable();
            $table->float('axy_mi_mi_ae')->nullable();
            $table->string('axy_mi_mi_af')->nullable();
            $table->string('axy_mi_mi_ag')->nullable();
            $table->string('axy_mi_mi_ah')->nullable();
            $table->string('axy_mi_mi_ai')->nullable();
            $table->string('axy_mi_mi_aj')->nullable();
            $table->string('axy_mi_mi_ak')->nullable();
            $table->double('axy_mi_mi_al')->nullable();
            $table->double('axy_mi_mi_am')->nullable();
            $table->double('axy_mi_mi_an')->nullable();
            $table->double('axy_mi_mi_ao')->nullable();
            $table->double('axy_mi_mi_ap')->nullable();
            $table->string('axy_mi_mi_aq')->nullable();
            $table->double('axy_mi_mi_ar')->nullable();
            $table->double('axy_mi_mi_as')->nullable();
            $table->double('axy_mi_mi_at')->nullable();
            $table->double('axy_mi_mi_au')->nullable();
            $table->string('axy_mi_mi_av')->nullable();
            $table->string('axy_mi_mi_aw')->nullable();
            $table->double('axy_mi_mi_ax')->nullable();
            $table->double('axy_mi_mi_ay')->nullable();
            $table->string('axy_mi_mi_az')->nullable();
            $table->string('axy_mi_mi_ba')->nullable();
            $table->string('axy_mi_mi_bb')->nullable();
            $table->string('axy_mi_mi_bc')->nullable();
            $table->double('axy_mi_mi_bd')->nullable();
            $table->double('axy_mi_mi_be')->nullable();
            $table->double('axy_mi_mi_bf')->nullable();
            $table->double('axy_mi_mi_bg')->nullable();
            $table->double('axy_mi_mi_bh')->nullable();
            $table->double('axy_mi_mi_bi')->nullable();
            $table->double('axy_mi_mi_bj')->nullable();
            $table->double('axy_mi_mi_bk')->nullable();
            $table->double('axy_mi_mi_bl')->nullable();
            $table->string('axy_mi_mi_bm')->nullable();
            $table->string('axy_mi_mi_bn')->nullable();
            $table->string('axy_mi_mi_bo')->nullable();
            $table->string('axy_mi_mi_bp')->nullable();
            $table->string('axy_mi_mi_bq')->nullable();
            $table->double('axy_mi_mi_br')->nullable();
            $table->double('axy_mi_mi_bs')->nullable();
            $table->double('axy_mi_mi_bt')->nullable();
            $table->double('axy_mi_mi_bu')->nullable();
            $table->double('axy_mi_mi_bv')->nullable();
            $table->double('axy_mi_mi_bw')->nullable();
            $table->double('axy_mi_mi_bx')->nullable();
            $table->double('axy_mi_mi_by')->nullable();
            $table->string('axy_mi_mi_bz')->nullable();
            $table->double('axy_mi_mi_ca')->nullable();
            $table->string('axy_mi_mi_cb')->nullable();
            $table->string('axy_mi_mi_cc')->nullable();
            $table->string('axy_mi_mi_cd')->nullable();
            $table->string('axy_mi_mi_ce')->nullable();
            $table->string('axy_mi_mi_cf')->nullable();
            $table->string('axy_mi_mi_cg')->nullable();
            $table->double('axy_mi_mi_ch')->nullable();
            $table->double('axy_mi_mi_ci')->nullable();
            $table->double('axy_mi_mi_cj')->nullable();
            $table->double('axy_mi_mi_ck')->nullable();
            $table->double('axy_mi_mi_cl')->nullable();
            $table->double('axy_mi_mi_cm')->nullable();
            $table->string('axy_mi_mi_cn')->nullable();
            $table->string('axy_mi_mi_co')->nullable();
            $table->string('axy_mi_mi_cp')->nullable();
            $table->string('axy_mi_mi_cq')->nullable();
            $table->string('axy_mi_mi_cr')->nullable();
            $table->double('axy_mi_mi_cs')->nullable();
            $table->double('axy_mi_mi_ct')->nullable();
            $table->double('axy_mi_mi_cu')->nullable();
            $table->double('axy_mi_mi_cv')->nullable();
            $table->double('axy_mi_mi_cw')->nullable();
            $table->double('axy_mi_mi_cx')->nullable();
            $table->string('axy_mi_mi_cy')->nullable();
            $table->double('axy_mi_mi_cz')->nullable();
            $table->string('axy_mi_mi_da')->nullable();
            $table->string('axy_mi_mi_db')->nullable();
            $table->string('axy_mi_mi_dc')->nullable();
            $table->string('axy_mi_mi_dd')->nullable();
            $table->string('axy_mi_mi_de')->nullable();
            $table->string('axy_mi_mi_df')->nullable();
            $table->double('axy_mi_mi_dg')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('axy_mi_mis');
    }
};
