<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('axy_invs', function (Blueprint $table) {
            $table->id();
            $table->string('axy_inv_a')->nullable();
            $table->string('axy_inv_b')->nullable();
            $table->string('axy_inv_c')->nullable();
            $table->string('axy_inv_d')->nullable();
            $table->string('axy_inv_e')->nullable();
            $table->string('axy_inv_f')->nullable();
            $table->double('axy_inv_g')->nullable();
            $table->double('axy_inv_h')->nullable();
            $table->double('axy_inv_i')->nullable();
            $table->double('axy_inv_j')->nullable();
            $table->double('axy_inv_k')->nullable();
            $table->double('axy_inv_l')->nullable();
            $table->double('axy_inv_m')->nullable();
            $table->double('axy_inv_n')->nullable();
            $table->double('axy_inv_o')->nullable();
            $table->double('axy_inv_p')->nullable();
            $table->double('axy_inv_q')->nullable();
            $table->string('axy_inv_r')->nullable();
            $table->string('axy_inv_s')->nullable();
            $table->string('axy_inv_t')->nullable();
            $table->string('axy_inv_u')->nullable();
            $table->string('axy_inv_v')->nullable();
            $table->float('axy_inv_w')->nullable();
            $table->float('axy_inv_x')->nullable();
            $table->float('axy_inv_y')->nullable();
            $table->float('axy_inv_z')->nullable();
            $table->float('axy_inv_aa')->nullable();
            $table->float('axy_inv_ab')->nullable();
            $table->float('axy_inv_ac')->nullable();
            $table->float('axy_inv_ad')->nullable();
            $table->float('axy_inv_ae')->nullable();
            $table->string('axy_inv_af')->nullable();
            $table->string('axy_inv_ag')->nullable();
            $table->string('axy_inv_ah')->nullable();
            $table->string('axy_inv_ai')->nullable();
            $table->string('axy_inv_aj')->nullable();
            $table->string('axy_inv_ak')->nullable();
            $table->double('axy_inv_al')->nullable();
            $table->double('axy_inv_am')->nullable();
            $table->double('axy_inv_an')->nullable();
            $table->double('axy_inv_ao')->nullable();
            $table->double('axy_inv_ap')->nullable();
            $table->string('axy_inv_aq')->nullable();
            $table->double('axy_inv_ar')->nullable();
            $table->double('axy_inv_as')->nullable();
            $table->double('axy_inv_at')->nullable();
            $table->double('axy_inv_au')->nullable();
            $table->string('axy_inv_av')->nullable();
            $table->string('axy_inv_aw')->nullable();
            $table->double('axy_inv_ax')->nullable();
            $table->double('axy_inv_ay')->nullable();
            $table->string('axy_inv_az')->nullable();
            $table->string('axy_inv_ba')->nullable();
            $table->string('axy_inv_bb')->nullable();
            $table->string('axy_inv_bc')->nullable();
            $table->double('axy_inv_bd')->nullable();
            $table->double('axy_inv_be')->nullable();
            $table->double('axy_inv_bf')->nullable();
            $table->double('axy_inv_bg')->nullable();
            $table->double('axy_inv_bh')->nullable();
            $table->double('axy_inv_bi')->nullable();
            $table->double('axy_inv_bj')->nullable();
            $table->double('axy_inv_bk')->nullable();
            $table->double('axy_inv_bl')->nullable();
            $table->string('axy_inv_bm')->nullable();
            $table->string('axy_inv_bn')->nullable();
            $table->string('axy_inv_bo')->nullable();
            $table->string('axy_inv_bp')->nullable();
            $table->string('axy_inv_bq')->nullable();
            $table->double('axy_inv_br')->nullable();
            $table->double('axy_inv_bs')->nullable();
            $table->double('axy_inv_bt')->nullable();
            $table->double('axy_inv_bu')->nullable();
            $table->double('axy_inv_bv')->nullable();
            $table->double('axy_inv_bw')->nullable();
            $table->double('axy_inv_bx')->nullable();
            $table->double('axy_inv_by')->nullable();
            $table->string('axy_inv_bz')->nullable();
            $table->double('axy_inv_ca')->nullable();
            $table->string('axy_inv_cb')->nullable();
            $table->string('axy_inv_cc')->nullable();
            $table->string('axy_inv_cd')->nullable();
            $table->string('axy_inv_ce')->nullable();
            $table->string('axy_inv_cf')->nullable();
            $table->string('axy_inv_cg')->nullable();
            $table->double('axy_inv_ch')->nullable();
            $table->double('axy_inv_ci')->nullable();
            $table->double('axy_inv_cj')->nullable();
            $table->double('axy_inv_ck')->nullable();
            $table->double('axy_inv_cl')->nullable();
            $table->double('axy_inv_cm')->nullable();
            $table->string('axy_inv_cn')->nullable();
            $table->string('axy_inv_co')->nullable();
            $table->string('axy_inv_cp')->nullable();
            $table->string('axy_inv_cq')->nullable();
            $table->string('axy_inv_cr')->nullable();
            $table->double('axy_inv_cs')->nullable();
            $table->double('axy_inv_ct')->nullable();
            $table->double('axy_inv_cu')->nullable();
            $table->double('axy_inv_cv')->nullable();
            $table->double('axy_inv_cw')->nullable();
            $table->double('axy_inv_cx')->nullable();
            $table->string('axy_inv_cy')->nullable();
            $table->double('axy_inv_cz')->nullable();
            $table->string('axy_inv_da')->nullable();
            $table->string('axy_inv_db')->nullable();
            $table->string('axy_inv_dc')->nullable();
            $table->string('axy_inv_dd')->nullable();
            $table->string('axy_inv_de')->nullable();
            $table->string('axy_inv_df')->nullable();
            $table->double('axy_inv_dg')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('axy_invs');
    }
};
