<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('axy_hi_his', function (Blueprint $table) {
            $table->id();
            $table->string('axy_hi_hi_a')->nullable();
            $table->string('axy_hi_hi_b')->nullable();
            $table->string('axy_hi_hi_c')->nullable();
            $table->string('axy_hi_hi_d')->nullable();
            $table->string('axy_hi_hi_e')->nullable();
            $table->string('axy_hi_hi_f')->nullable();
            $table->double('axy_hi_hi_g')->nullable();
            $table->double('axy_hi_hi_h')->nullable();
            $table->double('axy_hi_hi_i')->nullable();
            $table->double('axy_hi_hi_j')->nullable();
            $table->double('axy_hi_hi_k')->nullable();
            $table->double('axy_hi_hi_l')->nullable();
            $table->double('axy_hi_hi_m')->nullable();
            $table->double('axy_hi_hi_n')->nullable();
            $table->double('axy_hi_hi_o')->nullable();
            $table->double('axy_hi_hi_p')->nullable();
            $table->double('axy_hi_hi_q')->nullable();
            $table->string('axy_hi_hi_r')->nullable();
            $table->string('axy_hi_hi_s')->nullable();
            $table->string('axy_hi_hi_t')->nullable();
            $table->string('axy_hi_hi_u')->nullable();
            $table->string('axy_hi_hi_v')->nullable();
            $table->float('axy_hi_hi_w')->nullable();
            $table->float('axy_hi_hi_x')->nullable();
            $table->float('axy_hi_hi_y')->nullable();
            $table->float('axy_hi_hi_z')->nullable();
            $table->float('axy_hi_hi_aa')->nullable();
            $table->float('axy_hi_hi_ab')->nullable();
            $table->float('axy_hi_hi_ac')->nullable();
            $table->float('axy_hi_hi_ad')->nullable();
            $table->float('axy_hi_hi_ae')->nullable();
            $table->string('axy_hi_hi_af')->nullable();
            $table->string('axy_hi_hi_ag')->nullable();
            $table->string('axy_hi_hi_ah')->nullable();
            $table->string('axy_hi_hi_ai')->nullable();
            $table->string('axy_hi_hi_aj')->nullable();
            $table->string('axy_hi_hi_ak')->nullable();
            $table->double('axy_hi_hi_al')->nullable();
            $table->double('axy_hi_hi_am')->nullable();
            $table->double('axy_hi_hi_an')->nullable();
            $table->double('axy_hi_hi_ao')->nullable();
            $table->double('axy_hi_hi_ap')->nullable();
            $table->string('axy_hi_hi_aq')->nullable();
            $table->double('axy_hi_hi_ar')->nullable();
            $table->double('axy_hi_hi_as')->nullable();
            $table->double('axy_hi_hi_at')->nullable();
            $table->double('axy_hi_hi_au')->nullable();
            $table->string('axy_hi_hi_av')->nullable();
            $table->string('axy_hi_hi_aw')->nullable();
            $table->double('axy_hi_hi_ax')->nullable();
            $table->double('axy_hi_hi_ay')->nullable();
            $table->string('axy_hi_hi_az')->nullable();
            $table->string('axy_hi_hi_ba')->nullable();
            $table->string('axy_hi_hi_bb')->nullable();
            $table->string('axy_hi_hi_bc')->nullable();
            $table->double('axy_hi_hi_bd')->nullable();
            $table->double('axy_hi_hi_be')->nullable();
            $table->double('axy_hi_hi_bf')->nullable();
            $table->double('axy_hi_hi_bg')->nullable();
            $table->double('axy_hi_hi_bh')->nullable();
            $table->double('axy_hi_hi_bi')->nullable();
            $table->double('axy_hi_hi_bj')->nullable();
            $table->double('axy_hi_hi_bk')->nullable();
            $table->double('axy_hi_hi_bl')->nullable();
            $table->string('axy_hi_hi_bm')->nullable();
            $table->string('axy_hi_hi_bn')->nullable();
            $table->string('axy_hi_hi_bo')->nullable();
            $table->string('axy_hi_hi_bp')->nullable();
            $table->string('axy_hi_hi_bq')->nullable();
            $table->double('axy_hi_hi_br')->nullable();
            $table->double('axy_hi_hi_bs')->nullable();
            $table->double('axy_hi_hi_bt')->nullable();
            $table->double('axy_hi_hi_bu')->nullable();
            $table->double('axy_hi_hi_bv')->nullable();
            $table->double('axy_hi_hi_bw')->nullable();
            $table->double('axy_hi_hi_bx')->nullable();
            $table->double('axy_hi_hi_by')->nullable();
            $table->string('axy_hi_hi_bz')->nullable();
            $table->double('axy_hi_hi_ca')->nullable();
            $table->string('axy_hi_hi_cb')->nullable();
            $table->string('axy_hi_hi_cc')->nullable();
            $table->string('axy_hi_hi_cd')->nullable();
            $table->string('axy_hi_hi_ce')->nullable();
            $table->string('axy_hi_hi_cf')->nullable();
            $table->string('axy_hi_hi_cg')->nullable();
            $table->double('axy_hi_hi_ch')->nullable();
            $table->double('axy_hi_hi_ci')->nullable();
            $table->double('axy_hi_hi_cj')->nullable();
            $table->double('axy_hi_hi_ck')->nullable();
            $table->double('axy_hi_hi_cl')->nullable();
            $table->double('axy_hi_hi_cm')->nullable();
            $table->string('axy_hi_hi_cn')->nullable();
            $table->string('axy_hi_hi_co')->nullable();
            $table->string('axy_hi_hi_cp')->nullable();
            $table->string('axy_hi_hi_cq')->nullable();
            $table->string('axy_hi_hi_cr')->nullable();
            $table->double('axy_hi_hi_cs')->nullable();
            $table->double('axy_hi_hi_ct')->nullable();
            $table->double('axy_hi_hi_cu')->nullable();
            $table->double('axy_hi_hi_cv')->nullable();
            $table->double('axy_hi_hi_cw')->nullable();
            $table->double('axy_hi_hi_cx')->nullable();
            $table->string('axy_hi_hi_cy')->nullable();
            $table->double('axy_hi_hi_cz')->nullable();
            $table->string('axy_hi_hi_da')->nullable();
            $table->string('axy_hi_hi_db')->nullable();
            $table->string('axy_hi_hi_dc')->nullable();
            $table->string('axy_hi_hi_dd')->nullable();
            $table->string('axy_hi_hi_de')->nullable();
            $table->string('axy_hi_hi_df')->nullable();
            $table->double('axy_hi_hi_dg')->nullable();
            $table->double('axy_hi_hi_dh')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('axy_hi_his');
    }
};
