<?php

namespace App\Imports;

use App\Models\Axy_mv_mv;
use Maatwebsite\Excel\Concerns\ToModel;

class Axy_mv_Import implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Axy_mv_mv([
        'axy_mv_mv_a'=> $row[0],
        'axy_mv_mv_b'=> $row[1],
        'axy_mv_mv_c'=> $row[2],
        'axy_mv_mv_d'=> $row[3],
        'axy_mv_mv_e'=> $row[4],
        'axy_mv_mv_f'=> $row[5],
        'axy_mv_mv_g'=> $row[6],
        'axy_mv_mv_h'=> $row[7],
        'axy_mv_mv_i'=> $row[8],
        'axy_mv_mv_j'=> $row[9],
        'axy_mv_mv_k'=> $row[10],
        'axy_mv_mv_l'=> $row[11],
        'axy_mv_mv_m'=> $row[12],
        'axy_mv_mv_n'=> $row[13],
        'axy_mv_mv_o'=> $row[14],
        'axy_mv_mv_p'=> $row[15],
        'axy_mv_mv_q'=> $row[16],
        'axy_mv_mv_r'=> $row[17],
        'axy_mv_mv_s'=> $row[18],
        'axy_mv_mv_t'=> $row[19],
        'axy_mv_mv_u'=> $row[20],
        'axy_mv_mv_v'=> $row[21],
        'axy_mv_mv_w'=> $row[22],
        'axy_mv_mv_x'=> $row[23],
        'axy_mv_mv_y'=> $row[24],
        'axy_mv_mv_z'=> $row[25],
        'axy_mv_mv_aa'=> $row[26],
        'axy_mv_mv_ab'=> $row[27],
        'axy_mv_mv_ac'=> $row[28],
        'axy_mv_mv_ad'=> $row[29],
        'axy_mv_mv_ae'=> $row[30],
        'axy_mv_mv_af'=> $row[31],
        'axy_mv_mv_ag'=> $row[32],
        'axy_mv_mv_ah'=> $row[33],
        'axy_mv_mv_ai'=> $row[34],
        'axy_mv_mv_aj'=> $row[35],
        'axy_mv_mv_ak'=> $row[36],
        'axy_mv_mv_al'=> $row[37],
        'axy_mv_mv_am'=> $row[38],
        'axy_mv_mv_an'=> $row[39],
        'axy_mv_mv_ao'=> $row[40],
        'axy_mv_mv_ap'=> $row[41],
        'axy_mv_mv_aq'=> $row[42],
        'axy_mv_mv_ar'=> $row[43],
        'axy_mv_mv_as'=> $row[44],
        'axy_mv_mv_at'=> $row[45],
        'axy_mv_mv_au'=> $row[46],
        'axy_mv_mv_av'=> $row[47],
        'axy_mv_mv_aw'=> $row[48],
        'axy_mv_mv_ax'=> $row[49],
        'axy_mv_mv_ay'=> $row[50],
        'axy_mv_mv_az'=> $row[51],
        'axy_mv_mv_ba'=> $row[52],
        'axy_mv_mv_bb'=> $row[53],
        'axy_mv_mv_bc'=> $row[54],
        'axy_mv_mv_bd'=> $row[55],
        'axy_mv_mv_be'=> $row[56],
        'axy_mv_mv_bf'=> $row[57],
        'axy_mv_mv_bg'=> $row[58],
        'axy_mv_mv_bh'=> $row[59],
        'axy_mv_mv_bi'=> $row[60],
        'axy_mv_mv_bj'=> $row[61],
        'axy_mv_mv_bk'=> $row[62],
        'axy_mv_mv_bl'=> $row[63],
        'axy_mv_mv_bm'=> $row[64],
        'axy_mv_mv_bn'=> $row[65],
        'axy_mv_mv_bo'=> $row[66],
        'axy_mv_mv_bp'=> $row[67],
        'axy_mv_mv_bq'=> $row[68],
        'axy_mv_mv_br'=> $row[69],
        'axy_mv_mv_bs'=> $row[70],
        'axy_mv_mv_bt'=> $row[71],
        'axy_mv_mv_bu'=> $row[72],
        'axy_mv_mv_bv'=> $row[73],
        'axy_mv_mv_bw'=> $row[74],
        'axy_mv_mv_bx'=> $row[75],
        'axy_mv_mv_by'=> $row[76],
        'axy_mv_mv_bz'=> $row[77],
        'axy_mv_mv_ca'=> $row[78],
        'axy_mv_mv_cb'=> $row[79],
        'axy_mv_mv_cc'=> $row[80],
        'axy_mv_mv_cd'=> $row[81],
        'axy_mv_mv_ce'=> $row[82],
        'axy_mv_mv_cf'=> $row[83],
        'axy_mv_mv_cg'=> $row[84],
        'axy_mv_mv_ch'=> $row[85],
        'axy_mv_mv_ci'=> $row[86],
        'axy_mv_mv_cj'=> $row[87],
        'axy_mv_mv_ck'=> $row[88],
        'axy_mv_mv_cl'=> $row[89],
        'axy_mv_mv_cm'=> $row[90],
        'axy_mv_mv_cn'=> $row[91],
        'axy_mv_mv_co'=> $row[92],
        'axy_mv_mv_cp'=> $row[93],
        'axy_mv_mv_cq'=> $row[94],
        'axy_mv_mv_cr'=> $row[95],
        'axy_mv_mv_cs'=> $row[96],
        
        ]);
    }
}
