<?php

namespace App\Imports;

use App\Models\Axy_inv;
use Maatwebsite\Excel\Concerns\ToModel;

class Axy_inv_import implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Axy_inv([
            // 'axy_inv_a' => $row[0],
            // 'axy_inv_b' => $row[1],
            // 'axy_inv_c' => $row[2],
            // 'axy_inv_d' => $row[3],

        'axy_inv_a'=> $row[0],
        'axy_inv_b'=> $row[1],
        'axy_inv_c'=> $row[2],
        'axy_inv_d'=> $row[3],
        'axy_inv_e'=> $row[4],
        'axy_inv_f'=> $row[5],
        'axy_inv_g'=> $row[6],
        'axy_inv_h'=> $row[7],
        'axy_inv_i'=> $row[8],
        'axy_inv_j'=> $row[9],
        'axy_inv_k'=> $row[10],
        'axy_inv_l'=> $row[11],
        'axy_inv_m'=> $row[12],
        'axy_inv_n'=> $row[13],
        'axy_inv_o'=> $row[14],
        'axy_inv_p'=> $row[15],
        'axy_inv_q'=> $row[16],
        'axy_inv_r'=> $row[17],
        'axy_inv_s'=> $row[18],
        'axy_inv_t'=> $row[19],
        'axy_inv_u'=> $row[20],
        'axy_inv_v'=> $row[21],
        'axy_inv_w'=> $row[22],
        'axy_inv_x'=> $row[23],
        'axy_inv_y'=> $row[24],
        'axy_inv_z'=> $row[25],
        'axy_inv_aa'=> $row[26],
        'axy_inv_ab'=> $row[27],
        'axy_inv_ac'=> $row[28],
        'axy_inv_ad'=> $row[29],
        'axy_inv_ae'=> $row[30],
        'axy_inv_af'=> $row[31],
        'axy_inv_ag'=> $row[32],
        'axy_inv_ah'=> $row[33],
        'axy_inv_ai'=> $row[34],
        'axy_inv_aj'=> $row[35],
        'axy_inv_ak'=> $row[36],
        'axy_inv_al'=> $row[37],
        'axy_inv_am'=> $row[38],
        'axy_inv_an'=> $row[39],
        'axy_inv_ao'=> $row[40],
        'axy_inv_ap'=> $row[41],
        'axy_inv_aq'=> $row[42],
        'axy_inv_ar'=> $row[43],
        'axy_inv_as'=> $row[44],
        'axy_inv_at'=> $row[45],
        'axy_inv_au'=> $row[46],
        'axy_inv_av'=> $row[47],
        'axy_inv_aw'=> $row[48],
        'axy_inv_ax'=> $row[49],
        'axy_inv_ay'=> $row[50],
        'axy_inv_az'=> $row[51],
        'axy_inv_ba'=> $row[52],
        'axy_inv_bb'=> $row[53],
        'axy_inv_bc'=> $row[54],
        'axy_inv_bd'=> $row[55],
        'axy_inv_be'=> $row[56],
        'axy_inv_bf'=> $row[57],
        'axy_inv_bg'=> $row[58],
        'axy_inv_bh'=> $row[59],
        'axy_inv_bi'=> $row[60],
        'axy_inv_bj'=> $row[61],
        'axy_inv_bk'=> $row[62],
        'axy_inv_bl'=> $row[63],
        'axy_inv_bm'=> $row[64],
        'axy_inv_bn'=> $row[65],
        'axy_inv_bo'=> $row[66],
        'axy_inv_bp'=> $row[67],
        'axy_inv_bq'=> $row[68],
        'axy_inv_br'=> $row[69],
        'axy_inv_bs'=> $row[70],
        'axy_inv_bt'=> $row[71],
        'axy_inv_bu'=> $row[72],
        'axy_inv_bv'=> $row[73],
        'axy_inv_bw'=> $row[74],
        'axy_inv_bx'=> $row[75],
        'axy_inv_by'=> $row[76],
        'axy_inv_bz'=> $row[77],
        'axy_inv_ca'=> $row[78],
        'axy_inv_cb'=> $row[79],
        'axy_inv_cc'=> $row[80],
        'axy_inv_cd'=> $row[81],
        'axy_inv_ce'=> $row[82],
        'axy_inv_cf'=> $row[83],
        'axy_inv_cg'=> $row[84],
        'axy_inv_ch'=> $row[85],
        'axy_inv_ci'=> $row[86],
        'axy_inv_cj'=> $row[87],
        'axy_inv_ck'=> $row[88],
        'axy_inv_cl'=> $row[89],
        'axy_inv_cm'=> $row[90],
        'axy_inv_cn'=> $row[91],
        'axy_inv_co'=> $row[92],
        'axy_inv_cp'=> $row[93],
        'axy_inv_cq'=> $row[94],
        'axy_inv_cr'=> $row[95],
        'axy_inv_cs'=> $row[96],
        'axy_inv_ct'=> $row[97],
        'axy_inv_cu'=> $row[98],
        'axy_inv_cv'=> $row[99],
        'axy_inv_cw'=> $row[100],
        'axy_inv_cx'=> $row[101],
        'axy_inv_cy'=> $row[102],
        'axy_inv_cz'=> $row[103],
        'axy_inv_da'=> $row[104],
        'axy_inv_db'=> $row[105],
        'axy_inv_dc'=> $row[106],
        'axy_inv_dd'=> $row[107],
        'axy_inv_de'=> $row[108],
        'axy_inv_df'=> $row[109],
        'axy_inv_dg'=> $row[110],
        'axy_inv_dh'=> $row[111],


        ]);
    }
}
