<?php

namespace App\Imports;

use App\Models\Axy_hv_hv;
use Maatwebsite\Excel\Concerns\ToModel;

class Axy_hv_hv_Import implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Axy_hv_hv([
        'axy_hv_hv_a'=> $row[0],
        'axy_hv_hv_b'=> $row[1],
        'axy_hv_hv_c'=> $row[2],
        'axy_hv_hv_d'=> $row[3],
        'axy_hv_hv_e'=> $row[4],
        'axy_hv_hv_f'=> $row[5],
        'axy_hv_hv_g'=> $row[6],
        'axy_hv_hv_h'=> $row[7],
        'axy_hv_hv_i'=> $row[8],
        'axy_hv_hv_j'=> $row[9],
        'axy_hv_hv_k'=> $row[10],
        'axy_hv_hv_l'=> $row[11],
        'axy_hv_hv_m'=> $row[12],
        'axy_hv_hv_n'=> $row[13],
        'axy_hv_hv_o'=> $row[14],
        'axy_hv_hv_p'=> $row[15],
        'axy_hv_hv_q'=> $row[16],
        'axy_hv_hv_r'=> $row[17],
        'axy_hv_hv_s'=> $row[18],
        'axy_hv_hv_t'=> $row[19],
        'axy_hv_hv_u'=> $row[20],
        'axy_hv_hv_v'=> $row[21],
        'axy_hv_hv_w'=> $row[22],
        'axy_hv_hv_x'=> $row[23],
        'axy_hv_hv_y'=> $row[24],
        'axy_hv_hv_z'=> $row[25],
        'axy_hv_hv_aa'=> $row[26],
        'axy_hv_hv_ab'=> $row[27],
        'axy_hv_hv_ac'=> $row[28],
        'axy_hv_hv_ad'=> $row[29],
        'axy_hv_hv_ae'=> $row[30],
        'axy_hv_hv_af'=> $row[31],
        'axy_hv_hv_ag'=> $row[32],
        'axy_hv_hv_ah'=> $row[33],
        'axy_hv_hv_ai'=> $row[34],
        'axy_hv_hv_aj'=> $row[35],
        'axy_hv_hv_ak'=> $row[36],
        'axy_hv_hv_al'=> $row[37],
        'axy_hv_hv_am'=> $row[38],
        'axy_hv_hv_an'=> $row[39],
        'axy_hv_hv_ao'=> $row[40],
        'axy_hv_hv_ap'=> $row[41],
        'axy_hv_hv_aq'=> $row[42],
        'axy_hv_hv_ar'=> $row[43],
        'axy_hv_hv_as'=> $row[44],
        'axy_hv_hv_at'=> $row[45],
        'axy_hv_hv_au'=> $row[46],
        'axy_hv_hv_av'=> $row[47],
        'axy_hv_hv_aw'=> $row[48],
        'axy_hv_hv_ax'=> $row[49],
        'axy_hv_hv_ay'=> $row[50],
        'axy_hv_hv_az'=> $row[51],
        'axy_hv_hv_ba'=> $row[52],
        'axy_hv_hv_bb'=> $row[53],
        'axy_hv_hv_bc'=> $row[54],
        'axy_hv_hv_bd'=> $row[55],
        'axy_hv_hv_be'=> $row[56],
        'axy_hv_hv_bf'=> $row[57],
        'axy_hv_hv_bg'=> $row[58],
        'axy_hv_hv_bh'=> $row[59],
        'axy_hv_hv_bi'=> $row[60],
        'axy_hv_hv_bj'=> $row[61],
        'axy_hv_hv_bk'=> $row[62],
        'axy_hv_hv_bl'=> $row[63],
        'axy_hv_hv_bm'=> $row[64],
        'axy_hv_hv_bn'=> $row[65],
        'axy_hv_hv_bo'=> $row[66],
        'axy_hv_hv_bp'=> $row[67],
        'axy_hv_hv_bq'=> $row[68],
        'axy_hv_hv_br'=> $row[69],
        'axy_hv_hv_bs'=> $row[70],
        'axy_hv_hv_bt'=> $row[71],
        'axy_hv_hv_bu'=> $row[72],
        'axy_hv_hv_bv'=> $row[73],
        'axy_hv_hv_bw'=> $row[74],
        'axy_hv_hv_bx'=> $row[75],
        'axy_hv_hv_by'=> $row[76],
        'axy_hv_hv_bz'=> $row[77],
        'axy_hv_hv_ca'=> $row[78],
        'axy_hv_hv_cb'=> $row[79],
        'axy_hv_hv_cc'=> $row[80],
        'axy_hv_hv_cd'=> $row[81],
        'axy_hv_hv_ce'=> $row[82],
        'axy_hv_hv_cf'=> $row[83],
        'axy_hv_hv_cg'=> $row[84],
        'axy_hv_hv_ch'=> $row[85],
        'axy_hv_hv_ci'=> $row[86],
        'axy_hv_hv_cj'=> $row[87],
        'axy_hv_hv_ck'=> $row[88],
        'axy_hv_hv_cl'=> $row[89],
        'axy_hv_hv_cm'=> $row[90],
        'axy_hv_hv_cn'=> $row[91],
        'axy_hv_hv_co'=> $row[92],
        'axy_hv_hv_cp'=> $row[93],
        'axy_hv_hv_cq'=> $row[94],
        'axy_hv_hv_cr'=> $row[95],
        'axy_hv_hv_cs'=> $row[96],
        ]);
    }
}
