<?php

namespace App\Imports;

use App\Models\Dxy;
use Maatwebsite\Excel\Concerns\ToModel;

class DxyImport implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Dxy([
        'dxy_a'=> $row[0],
        'dxy_b'=> $row[1],
        'dxy_c'=> $row[2],
        'dxy_d'=> $row[3],
        'dxy_e'=> $row[4],
        'dxy_f'=> $row[5],
        'dxy_g'=> $row[6],
        'dxy_h'=> $row[7],
        'dxy_i'=> $row[8],
        'dxy_j'=> $row[9],
        'dxy_k'=> $row[10],
        'dxy_l'=> $row[11],
        'dxy_m'=> $row[12],
        'dxy_n'=> $row[13],
        'dxy_o'=> $row[14],
        'dxy_p'=> $row[15],
        'dxy_q'=> $row[16],
        'dxy_r'=> $row[17],
        'dxy_s'=> $row[18],
        'dxy_t'=> $row[19],
        'dxy_u'=> $row[20],
        'dxy_v'=> $row[21],
        'dxy_w'=> $row[22],
        'dxy_x'=> $row[23],
        'dxy_y'=> $row[24],
        'dxy_z'=> $row[25],
        'dxy_aa'=> $row[26],
        'dxy_ab'=> $row[27],
        'dxy_ac'=> $row[28],
        'dxy_ad'=> $row[29],
        'dxy_ae'=> $row[30],
        'dxy_af'=> $row[31],
        'dxy_ag'=> $row[32],
        'dxy_ah'=> $row[33],
        'dxy_ai'=> $row[34],
        'dxy_aj'=> $row[35],
        'dxy_ak'=> $row[36],
        'dxy_al'=> $row[37],
        'dxy_am'=> $row[38],
        'dxy_an'=> $row[39],
        'dxy_ao'=> $row[40],
        'dxy_ap'=> $row[41],
        'dxy_aq'=> $row[42],
        'dxy_ar'=> $row[43],
        'dxy_as'=> $row[44],
        'dxy_at'=> $row[45],
        'dxy_au'=> $row[46],
        'dxy_av'=> $row[47],
        'dxy_aw'=> $row[48],
        'dxy_ax'=> $row[49],
        'dxy_ay'=> $row[50],
        'dxy_az'=> $row[51],
        'dxy_ba'=> $row[52],
        'dxy_bb'=> $row[53],
        'dxy_bc'=> $row[54],
        'dxy_bd'=> $row[55],
        'dxy_be'=> $row[56],
        'dxy_bf'=> $row[57],
        'dxy_bg'=> $row[58],
        'dxy_bh'=> $row[59],
        'dxy_bi'=> $row[60],
        'dxy_bj'=> $row[61],
        'dxy_bk'=> $row[62],
        'dxy_bl'=> $row[63],
        'dxy_bm'=> $row[64],
        'dxy_bn'=> $row[65],
        'dxy_bo'=> $row[66],
        'dxy_bp'=> $row[67],
        'dxy_bq'=> $row[68],
        'dxy_br'=> $row[69],
        'dxy_bs'=> $row[70],
        'dxy_bt'=> $row[71],
        'dxy_bu'=> $row[72],
        'dxy_bv'=> $row[73],
        'dxy_bw'=> $row[74],
        'dxy_bx'=> $row[75],
        'dxy_by'=> $row[76],
        'dxy_bz'=> $row[77],
        'dxy_ca'=> $row[78],
        'dxy_cb'=> $row[79],
        'dxy_cc'=> $row[80],
        'dxy_cd'=> $row[81],
        'dxy_ce'=> $row[82],
        'dxy_cf'=> $row[83],
        'dxy_cg'=> $row[84],
        'dxy_ch'=> $row[85],
        'dxy_ci'=> $row[86],
        'dxy_cj'=> $row[87],
        'dxy_ck'=> $row[88],
        'dxy_cl'=> $row[89],
        'dxy_cm'=> $row[90],
        'dxy_cn'=> $row[91],
        'dxy_co'=> $row[92],
        'dxy_cp'=> $row[93],
        'dxy_cq'=> $row[94],
        'dxy_cr'=> $row[95],
        'dxy_cs'=> $row[96],
        ]);
    }
}
