<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Axy_hi_mv extends Model
{
    use HasFactory;

    protected $fillable = [
        'axy_hi_mv_a',
        'axy_hi_mv_b',
        'axy_hi_mv_c',
        'axy_hi_mv_d',
        'axy_hi_mv_e',
        'axy_hi_mv_f',
        'axy_hi_mv_g',
        'axy_hi_mv_h',
        'axy_hi_mv_i',
        'axy_hi_mv_j',
        'axy_hi_mv_k',
        'axy_hi_mv_l',
        'axy_hi_mv_m',
        'axy_hi_mv_n',
        'axy_hi_mv_o',
        'axy_hi_mv_p',
        'axy_hi_mv_q',
        'axy_hi_mv_r',
        'axy_hi_mv_s',
        'axy_hi_mv_t',
        'axy_hi_mv_u',
        'axy_hi_mv_v',
        'axy_hi_mv_w',
        'axy_hi_mv_x',
        'axy_hi_mv_y',
        'axy_hi_mv_z',
        'axy_hi_mv_aa',
        'axy_hi_mv_ab',
        'axy_hi_mv_ac',
        'axy_hi_mv_ad',
        'axy_hi_mv_ae',
        'axy_hi_mv_af',
        'axy_hi_mv_ag',
        'axy_hi_mv_ah',
        'axy_hi_mv_ai',
        'axy_hi_mv_aj',
        'axy_hi_mv_ak',
        'axy_hi_mv_al',
        'axy_hi_mv_am',
        'axy_hi_mv_an',
        'axy_hi_mv_ao',
        'axy_hi_mv_ap',
        'axy_hi_mv_aq',
        'axy_hi_mv_ar',
        'axy_hi_mv_as',
        'axy_hi_mv_at',
        'axy_hi_mv_au',
        'axy_hi_mv_av',
        'axy_hi_mv_aw',
        'axy_hi_mv_ax',
        'axy_hi_mv_ay',
        'axy_hi_mv_az',
        'axy_hi_mv_ba',
        'axy_hi_mv_bb',
        'axy_hi_mv_bc',
        'axy_hi_mv_bd',
        'axy_hi_mv_be',
        'axy_hi_mv_bf',
        'axy_hi_mv_bg',
        'axy_hi_mv_bh',
        'axy_hi_mv_bi',
        'axy_hi_mv_bj',
        'axy_hi_mv_bk',
        'axy_hi_mv_bl',
        'axy_hi_mv_bm',
        'axy_hi_mv_bn',
        'axy_hi_mv_bo',
        'axy_hi_mv_bp',
        'axy_hi_mv_bq',
        'axy_hi_mv_br',
        'axy_hi_mv_bs',
        'axy_hi_mv_bt',
        'axy_hi_mv_bu',
        'axy_hi_mv_bv',
        'axy_hi_mv_bw',
        'axy_hi_mv_bx',
        'axy_hi_mv_by',
        'axy_hi_mv_bz',
        'axy_hi_mv_ca',
        'axy_hi_mv_cb',
        'axy_hi_mv_cc',
        'axy_hi_mv_cd',
        'axy_hi_mv_ce',
        'axy_hi_mv_cf',
        'axy_hi_mv_cg',
        'axy_hi_mv_ch',
        'axy_hi_mv_ci',
        'axy_hi_mv_cj',
        'axy_hi_mv_ck',
        'axy_hi_mv_cl',
        'axy_hi_mv_cm',
        'axy_hi_mv_cn',
        'axy_hi_mv_co',
        'axy_hi_mv_cp',
        'axy_hi_mv_cq',
        'axy_hi_mv_cr',
        'axy_hi_mv_cs',
       
        
    ];
}
