<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Axy_mv_mv extends Model
{
    use HasFactory;

    protected $fillable = [
        'axy_mv_mv_a',
        'axy_mv_mv_b',
        'axy_mv_mv_c',
        'axy_mv_mv_d',
        'axy_mv_mv_e',
        'axy_mv_mv_f',
        'axy_mv_mv_g',
        'axy_mv_mv_h',
        'axy_mv_mv_i',
        'axy_mv_mv_j',
        'axy_mv_mv_k',
        'axy_mv_mv_l',
        'axy_mv_mv_m',
        'axy_mv_mv_n',
        'axy_mv_mv_o',
        'axy_mv_mv_p',
        'axy_mv_mv_q',
        'axy_mv_mv_r',
        'axy_mv_mv_s',
        'axy_mv_mv_t',
        'axy_mv_mv_u',
        'axy_mv_mv_v',
        'axy_mv_mv_w',
        'axy_mv_mv_x',
        'axy_mv_mv_y',
        'axy_mv_mv_z',
        'axy_mv_mv_aa',
        'axy_mv_mv_ab',
        'axy_mv_mv_ac',
        'axy_mv_mv_ad',
        'axy_mv_mv_ae',
        'axy_mv_mv_af',
        'axy_mv_mv_ag',
        'axy_mv_mv_ah',
        'axy_mv_mv_ai',
        'axy_mv_mv_aj',
        'axy_mv_mv_ak',
        'axy_mv_mv_al',
        'axy_mv_mv_am',
        'axy_mv_mv_an',
        'axy_mv_mv_ao',
        'axy_mv_mv_ap',
        'axy_mv_mv_aq',
        'axy_mv_mv_ar',
        'axy_mv_mv_as',
        'axy_mv_mv_at',
        'axy_mv_mv_au',
        'axy_mv_mv_av',
        'axy_mv_mv_aw',
        'axy_mv_mv_ax',
        'axy_mv_mv_ay',
        'axy_mv_mv_az',
        'axy_mv_mv_ba',
        'axy_mv_mv_bb',
        'axy_mv_mv_bc',
        'axy_mv_mv_bd',
        'axy_mv_mv_be',
        'axy_mv_mv_bf',
        'axy_mv_mv_bg',
        'axy_mv_mv_bh',
        'axy_mv_mv_bi',
        'axy_mv_mv_bj',
        'axy_mv_mv_bk',
        'axy_mv_mv_bl',
        'axy_mv_mv_bm',
        'axy_mv_mv_bn',
        'axy_mv_mv_bo',
        'axy_mv_mv_bp',
        'axy_mv_mv_bq',
        'axy_mv_mv_br',
        'axy_mv_mv_bs',
        'axy_mv_mv_bt',
        'axy_mv_mv_bu',
        'axy_mv_mv_bv',
        'axy_mv_mv_bw',
        'axy_mv_mv_bx',
        'axy_mv_mv_by',
        'axy_mv_mv_bz',
        'axy_mv_mv_ca',
        'axy_mv_mv_cb',
        'axy_mv_mv_cc',
        'axy_mv_mv_cd',
        'axy_mv_mv_ce',
        'axy_mv_mv_cf',
        'axy_mv_mv_cg',
        'axy_mv_mv_ch',
        'axy_mv_mv_ci',
        'axy_mv_mv_cj',
        'axy_mv_mv_ck',
        'axy_mv_mv_cl',
        'axy_mv_mv_cm',
        'axy_mv_mv_cn',
        'axy_mv_mv_co',
        'axy_mv_mv_cp',
        'axy_mv_mv_cq',
        'axy_mv_mv_cr',
        'axy_mv_mv_cs',
       
        
    ];
}
