<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dxy extends Model
{
    use HasFactory;

    protected $fillable = [
        'dxy_a',
        'dxy_b',
        'dxy_c',
        'dxy_d',
        'dxy_e',
        'dxy_f',
        'dxy_g',
        'dxy_h',
        'dxy_i',
        'dxy_j',
        'dxy_k',
        'dxy_l',
        'dxy_m',
        'dxy_n',
        'dxy_o',
        'dxy_p',
        'dxy_q',
        'dxy_r',
        'dxy_s',
        'dxy_t',
        'dxy_u',
        'dxy_v',
        'dxy_w',
        'dxy_x',
        'dxy_y',
        'dxy_z',
        'dxy_aa',
        'dxy_ab',
        'dxy_ac',
        'dxy_ad',
        'dxy_ae',
        'dxy_af',
        'dxy_ag',
        'dxy_ah',
        'dxy_ai',
        'dxy_aj',
        'dxy_ak',
        'dxy_al',
        'dxy_am',
        'dxy_an',
        'dxy_ao',
        'dxy_ap',
        'dxy_aq',
        'dxy_ar',
        'dxy_as',
        'dxy_at',
        'dxy_au',
        'dxy_av',
        'dxy_aw',
        'dxy_ax',
        'dxy_ay',
        'dxy_az',
        'dxy_ba',
        'dxy_bb',
        'dxy_bc',
        'dxy_bd',
        'dxy_be',
        'dxy_bf',
        'dxy_bg',
        'dxy_bh',
        'dxy_bi',
        'dxy_bj',
        'dxy_bk',
        'dxy_bl',
        'dxy_bm',
        'dxy_bn',
        'dxy_bo',
        'dxy_bp',
        'dxy_bq',
        'dxy_br',
        'dxy_bs',
        'dxy_bt',
        'dxy_bu',
        'dxy_bv',
        'dxy_bw',
        'dxy_bx',
        'dxy_by',
        'dxy_bz',
        'dxy_ca',
        'dxy_cb',
        'dxy_cc',
        'dxy_cd',
        'dxy_ce',
        'dxy_cf',
        'dxy_cg',
        'dxy_ch',
        'dxy_ci',
        'dxy_cj',
        'dxy_ck',
        'dxy_cl',
        'dxy_cm',
        'dxy_cn',
        'dxy_co',
        'dxy_cp',
        'dxy_cq',
        'dxy_cr',
        'dxy_cs',
       
        
    ];
}
